import { useState, type DragEvent } from 'react';
import { AdminLayout } from '../../components/layouts';
import { Card, DataTable, Icon, PageHeader } from '../../components/common/ui';
import { periods, subjects, useTimetable, weekdays, type SlotId } from '../../stores/timetableStore';

const Summary = ({ items }: { items: string[][] }) => <div className="stats">{items.map(([value, label, icon]) => <Card key={label}><Icon>{icon}</Icon><strong>{value}</strong><span>{label}</span></Card>)}</div>;

export function Exams() { return <AdminLayout><PageHeader title="Exam and Results Management" subtitle="Schedule examinations and monitor grading progress." /><Summary items={[['04', 'Upcoming exams', 'event'], ['82%', 'Average score', 'analytics'], ['68%', 'Grading progress', 'task_alt']]} /><Card><h2>Upcoming Examinations</h2><DataTable headers={['Subject', 'Date', 'Hall', 'Proctor', 'Status']} rows={[['Mathematics', 'Oct 24, 2024', 'Hall A', 'Mr. Davis', 'Scheduled'], ['Physics', 'Oct 26, 2024', 'Hall B', 'Mrs. Chen', 'Scheduled'], ['Chemistry', 'Oct 29, 2024', 'Lab 2', 'Ms. Lee', 'Draft']]} /></Card></AdminLayout>; }

export function Documents() { return <AdminLayout><PageHeader title="Administrative Paperwork Manager" subtitle="Manage document requests from one place." /><Card className="dropzone"><Icon>cloud_upload</Icon><h2>Upload a document</h2><p>Drag and drop files here, or browse from your device</p><button className="primary-btn">Choose file</button></Card><Card><h2>Digitized Documents Requests</h2><DataTable headers={['Document', 'Category', 'Requested by', 'Date', 'Status']} rows={[['Transfer Certificate', 'Student records', 'Anita Roy', 'Oct 22, 2024', 'Pending'], ['Fee Receipt Q3', 'Finance', 'Ravi Kumar', 'Oct 21, 2024', 'Processing'], ['Bonafide Certificate', 'Student records', 'Nisha Shah', 'Oct 19, 2024', 'Completed']]} /></Card></AdminLayout>; }

export function Activities() { const clubs = ['Debate Club', 'Soccer Match: Varsity vs. Oakwood', 'Art Exhibition Setup', 'Premiers Club']; return <AdminLayout><PageHeader title="Student Activities Dashboard" subtitle="Monitor events, clubs, and student engagement." /><div className="activity-grid"><div><h2>Upcoming Events & Clubs</h2><div className="club-grid">{clubs.map((club, i) => <Card key={club}><div className="club-icon"><Icon>celebration</Icon></div><h3>{club}</h3><p>Next: <b>Oct {27 + i}</b></p><p>Supervisor: <b>Mrs. Chen</b></p><p>Enrollment: <b>{45 - i * 5}/50</b></p></Card>)}</div></div><Card><h2>Recent Activity Feed</h2><div className="feed">{['Science Club submitted project report', 'New Chess Club members registered', 'Basketball practice scheduled'].map(activity => <div key={activity}><i className="current" /><p>{activity}<small>Today, 10:30 AM</small></p></div>)}</div></Card></div></AdminLayout>; }

export function Timetable() {
  const { state, assign, clear, setClass, save } = useTimetable();
  const [isDragging, setIsDragging] = useState(false);
  const [dragTarget, setDragTarget] = useState<SlotId | null>(null);
  const onDrop = (event: DragEvent<HTMLDivElement>, slotId: SlotId) => { event.preventDefault(); const subject = event.dataTransfer.getData('text/plain'); if (subject) assign(slotId, subject); setIsDragging(false); setDragTarget(null); };
  return <AdminLayout><PageHeader title="Drag and Drop Timetable Builder" subtitle="Build weekly schedules for every grade and section." /><div className="timetable-toolbar"><label>Grade<select value={state.grade} onChange={event => setClass(event.target.value, state.section)}><option>10</option><option>11</option><option>12</option></select></label><label>Section<select value={state.section} onChange={event => setClass(state.grade, event.target.value)}><option>A</option><option>B</option><option>C</option></select></label><span className="sync-state">{state.saving ? 'Saving…' : state.dirty ? 'Unsaved changes' : state.lastSavedAt ? 'All changes saved' : 'Ready'}</span><button className="primary-btn" disabled={!state.dirty || state.saving} onClick={save}><Icon>save</Icon>{state.saving ? 'Saving' : 'Save timetable'}</button></div><div className="timetable-layout"><Card><h2>Subjects & Classrooms</h2>{subjects.map((subject, i) => <div className="palette-item" draggable onDragStart={event => { event.dataTransfer.setData('text/plain', subject); setIsDragging(true); }} onDragEnd={() => { setIsDragging(false); setDragTarget(null); }} key={subject}><span className={`swatch s${i}`} />{subject}<Icon>drag_indicator</Icon></div>)}</Card><Card className="timetable"><h2>Grade {state.grade} • Section {state.section}</h2><div className="schedule-grid"><b>Time</b>{weekdays.map(day => <b key={day}>{day}</b>)}{periods.map(time => <><span className="time" key={time}>{time}</span>{weekdays.map(day => { const id = `${day}-${time}` as SlotId; const slot = state.slots.find(item => item.id === id); const classes = `slot ${slot?.subject ? 'filled' : ''} ${isDragging ? 'dragging' : ''} ${dragTarget === id ? 'drag-target' : ''}`; return <div className={classes} key={id} onDragEnter={() => setDragTarget(id)} onDragOver={event => event.preventDefault()} onDragLeave={() => setDragTarget(null)} onDrop={event => onDrop(event, id)} onDoubleClick={() => slot?.subject && clear(id)}>{slot?.subject || 'Drop subject'}</div>; })}</>)}</div><p className="timetable-help"><Icon>info</Icon>Drag a subject into a slot. Double-click a filled slot to clear it.</p></Card></div></AdminLayout>;
}
