import { useEffect, useState } from 'react';
import { Card, Icon, PageHeader, Status } from '../../components/common/ui';
import { StudentLayout } from '../../components/layouts';
import type { Role } from '../../app/App';
import { request } from '../../services/api/client';
import { applyDemoScan, demoAttendanceRecords, getAttendanceOverview, scanAttendance, type AttendanceOverview } from '../../services/api/attendance';

export function Login({ onLogin }: { onLogin: (role: Role, permissions: string[]) => void }) {
  const [role, setRole] = useState<Role>('admin');
  const [email, setEmail] = useState('admin@edusync.local');
  const [password, setPassword] = useState('Admin@123');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const credentials: Record<Role, { email: string; password: string; permissions: string[] }> = { admin: { email: 'admin@edusync.local', password: 'Admin@123', permissions: [] }, teacher: { email: 'teacher@edusync.local', password: 'Teacher@123', permissions: ['manage_assignments', 'manage_exams'] }, student: { email: 'student@edusync.local', password: 'Student@123', permissions: [] } };
  const selectRole = (nextRole: Role) => { setRole(nextRole); setEmail(credentials[nextRole].email); setPassword(credentials[nextRole].password); setError(''); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const account = credentials[role]; if (email.trim().toLowerCase() !== account.email || password !== account.password) { setError('Invalid demo credentials for this role.'); return; } setLoading(true); setError(''); try { const response = await request<{ access_token: string; user: { id: string; role: Role; permissions: string[] } }>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('edusync-token', response.access_token); localStorage.setItem('edusync-user-id', response.user.id); onLogin(response.user.role, response.user.permissions); } catch { setError('The API could not sign you in. Start Docker and run the seed command first.'); } finally { setLoading(false); } };
  return <main className="login-page"><section className="login-card"><div className="brand login-brand"><span className="brand-mark"><Icon>school</Icon></span>EduSync ERP</div><span className="eyebrow">WELCOME BACK</span><h1>Sign in to your campus</h1><p className="login-subtitle">Admin access is ready. Select a role or use the demo credentials below.</p><div className="role-options"><button type="button" className={role === 'admin' ? 'selected' : ''} onClick={() => selectRole('admin')}><span className="role-icon admin-role"><Icon>admin_panel_settings</Icon></span><span><strong>Admin Login</strong><small>Full system access and teacher management</small></span><Icon>arrow_forward</Icon></button><button type="button" className={role === 'teacher' ? 'selected' : ''} onClick={() => selectRole('teacher')}><span className="role-icon teacher-role"><Icon>person_book</Icon></span><span><strong>Teacher Login</strong><small>Access granted permissions only</small></span><Icon>arrow_forward</Icon></button><button type="button" className={role === 'student' ? 'selected' : ''} onClick={() => selectRole('student')}><span className="role-icon student-role"><Icon>school</Icon></span><span><strong>Student Login</strong><small>Own assignments, results and profile</small></span><Icon>arrow_forward</Icon></button></div><form className="login-form" onSubmit={submit}><label>Email<input value={email} onChange={event => setEmail(event.target.value)} type="email" /></label><label>Password<input value={password} onChange={event => setPassword(event.target.value)} type="password" /></label>{error && <p className="login-error">{error}</p>}<button className="primary-btn login-submit" disabled={loading} type="submit">{loading ? 'Signing in…' : `Continue as ${role}`}</button></form><p className="demo-note"><Icon>info</Icon>Demo: {credentials[role].email} / {credentials[role].password}</p></section></main>;
}

function formatScanTime(value?: string | null) { return value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'No scan yet'; }
function useAttendancePolling() { const [attendance, setAttendance] = useState<AttendanceOverview | null>(demoAttendanceRecords[0]); useEffect(() => { let active = true; const load = async () => { try { const next = await getAttendanceOverview(); if (active) setAttendance(next); } catch { if (active) setAttendance(demoAttendanceRecords[0]); } }; void load(); const timer = window.setInterval(load, 5000); return () => { active = false; window.clearInterval(timer); }; }, []); return attendance; }

export function StudentDashboard() { const attendance = useAttendancePolling(); const events = [['science', 'Science Exhibition', '20 Days Left'], ['celebration', 'Annual Function Day', '5 Days Left'], ['today', 'My Day', '7 Days Left']]; return <StudentLayout><PageHeader title="Hello, Shashi Kant!" subtitle="Here's your academic overview for today." /><section className="student-overview-grid"><Card className="attendance-live-card"><div className="card-title"><h2>Attendance</h2><span className={`status ${attendance?.today_status === 'present' ? 'present' : 'pending'}`}>{attendance?.today_status === 'present' ? 'Recorded today' : 'Waiting scan'}</span></div><strong>{attendance ? `${attendance.attendance_percentage}%` : '...'}</strong><p>{attendance?.latest_scan_at ? `Last NFC scan: ${formatScanTime(attendance.latest_scan_at)}` : 'Scan the NFC ID card to mark attendance.'}</p><div className="attendance-mini-stats"><span><b>{attendance?.present_days ?? 0}</b>Present</span><span><b>{attendance?.late_days ?? 0}</b>Late</span><span><b>{attendance?.recorded_days ?? 0}</b>Records</span></div></Card><Card><h2>My Progress</h2><div className="progress-chart compact-progress">{[65, 78, 58, 86, 72, 92, 80].map((height, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${height}%` }} /><span>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][i]}</span></div>)}</div></Card></section><section className="section"><h2>Upcoming Events</h2><div className="event-grid">{events.map(([icon, title, date]) => <Card className="event-card" key={title}><div className="event-icon"><Icon>{icon}</Icon></div><div><b>{title}</b><span>{date}</span></div><Icon>chevron_right</Icon></Card>)}</div></section><Card className="announcement"><div><span className="label">ANNOUNCEMENT</span><h2>Important Update:<br />School Holiday</h2><p>Due to national holiday, the campus will remain closed this Friday.</p><button className="light-btn">Read more <Icon>arrow_forward</Icon></button></div><Icon>campaign</Icon></Card></StudentLayout>; }

export function StudentTimetable() { const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']; const periods: Array<[string, string[]]> = [['09:00', ['Mathematics', 'English', 'Physics', 'Chemistry', 'Mathematics']], ['10:00', ['Physics', 'Mathematics', 'English', 'Computer Lab', 'Chemistry']], ['11:30', ['Chemistry', 'Physics', 'Mathematics', 'English', 'Computer Lab']], ['01:00', ['Computer Lab', 'Physical Education', 'Chemistry', 'Mathematics', 'English']]]; return <StudentLayout><PageHeader title="My Timetable" subtitle="Grade 12 • Section A · Weekly class schedule" /><Card className="student-timetable"><div className="schedule-grid"><b>Time</b>{days.map(day => <b key={day}>{day}</b>)}{periods.map(([time, subjects]) => <><span className="time" key={time}>{time}</span>{subjects.map((subject, index) => <div className="slot filled" key={`${time}-${days[index]}`}>{subject}</div>)}</>)}</div><p className="timetable-help"><Icon>info</Icon>Your school timetable is shown here. Contact your teacher or administrator if a change is needed.</p></Card></StudentLayout>; }

export function Assignments() { const items = [['Compiler Design Lab 4', 'Compiler Design', 'Due tomorrow', 'Pending'], ['Flutter UI Prototype', 'Mobile Application', 'Due Oct 30', 'Submitted'], ['Neural Networks Research Paper', 'Artificial Intelligence', 'Due Nov 05', 'Graded']]; return <StudentLayout><PageHeader title="Assignments" subtitle="Keep track of your coursework and deadlines." action="New Assignment" /><div className="filter-row">{['All', 'Pending', 'Submitted', 'Graded'].map((filter, i) => <button className={`filter ${i === 0 ? 'active' : ''}`} key={filter}>{filter}</button>)}</div>{items.map(([title, subject, due, status]) => <Card className="assignment" key={title}><div className="subject-icon"><Icon>description</Icon></div><div className="assignment-info"><span className="eyebrow">{subject}</span><h2>{title}</h2><p><Icon>calendar_today</Icon>{due}</p></div><Status>{status}</Status><button className="icon-btn"><Icon>more_vert</Icon></button></Card>)}</StudentLayout>; }

export function StudentAttendance() { const attendance = useAttendancePolling(); return <StudentLayout><PageHeader title="My Attendance" subtitle="Live NFC attendance and recent history" /><div className="attendance-dashboard-grid"><Card className="attendance-live-card"><div className="card-title"><h2>Today</h2><span className={`status ${attendance?.today_status === 'present' ? 'present' : 'pending'}`}>{attendance?.today_status === 'present' ? 'Present' : 'Not marked'}</span></div><strong>{attendance ? `${attendance.attendance_percentage}%` : '...'}</strong><p>{attendance?.latest_scan_at ? `Latest scan: ${formatScanTime(attendance.latest_scan_at)}` : 'No NFC scan has been recorded today.'}</p></Card><Card><h2>Summary</h2><div className="attendance-mini-stats large"><span><b>{attendance?.present_days ?? 0}</b>Present</span><span><b>{attendance?.late_days ?? 0}</b>Late</span><span><b>{attendance?.recorded_days ?? 0}</b>Total</span></div></Card></div><Card><div className="card-title"><h2>Attendance History</h2><span className="muted">Student code {attendance?.student_code || 'STU-DEMO-001'}</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Status</th><th>Source</th><th>Scan time</th><th>Note</th></tr></thead><tbody>{attendance?.records.length ? attendance.records.map(record => <tr key={record.id}><td>{new Date(record.date).toLocaleDateString()}</td><td><Status>{record.status}</Status></td><td>{record.source.toUpperCase()}</td><td>{formatScanTime(record.scanned_at)}</td><td>{record.notes || '-'}</td></tr>) : <tr><td colSpan={5}>No attendance records yet.</td></tr>}</tbody></table></div></Card></StudentLayout>; }

export function AttendanceScan() { const [status, setStatus] = useState<'loading' | 'success' | 'error'>('loading'); const [message, setMessage] = useState('Reading NFC card...'); const [attendance, setAttendance] = useState<AttendanceOverview | null>(null); useEffect(() => { const params = new URLSearchParams(window.location.search); const card = params.get('card') || params.get('uid') || 'DEMO-NFC-001'; void scanAttendance(card).then(result => { setStatus('success'); setMessage(result.created ? 'Attendance recorded successfully.' : 'Attendance was already recorded today, so the scan time was updated.'); setAttendance(result.attendance); }).catch(() => { try { const result = applyDemoScan(card); setStatus('success'); setMessage('Demo attendance recorded locally. Run backend migration/seed for real database scan.'); setAttendance(result); } catch (error) { setStatus('error'); setMessage(error instanceof Error ? error.message : 'Unable to record attendance.'); } }); }, []); return <main className="login-page"><section className="scan-card"><div className={`scan-icon ${status}`}><Icon>{status === 'success' ? 'check_circle' : status === 'error' ? 'error' : 'nfc'}</Icon></div><span className="eyebrow">NFC ATTENDANCE</span><h1>{status === 'loading' ? 'Recording attendance' : status === 'success' ? 'Attendance recorded' : 'Scan failed'}</h1><p>{message}</p>{attendance && <div className="scan-result"><b>{attendance.student_name}</b><span>{attendance.grade} • Section {attendance.section}</span><small>{formatScanTime(attendance.latest_scan_at)}</small></div>}<button className="primary-btn" onClick={() => window.location.href = '/'}><Icon>home</Icon>Go to dashboard</button></section></main>; }

export function Profile() { const attendance = useAttendancePolling(); const stats = [['4.2', 'GPA'], [attendance ? `${attendance.attendance_percentage}%` : '...', 'Attendance'], ['12/15', 'Assignments']]; return <StudentLayout><Card className="profile-hero"><div className="profile-avatar">SK</div><div><h1>Shashi Kant</h1><p>Grade 12 • Section A</p><span className="muted">Student ID: STU-2024-018</span></div><button className="outline-btn"><Icon>edit</Icon>Edit profile</button></Card><div className="stats">{stats.map(([value, label]) => <Card key={label}><strong>{value}</strong><span>{label}</span></Card>)}</div><Card className="insight"><div className="insight-icon"><Icon>auto_awesome</Icon></div><div><span className="eyebrow">AI PERFORMANCE INSIGHT</span><h2>You're building strong momentum</h2><p>{attendance?.today_status === 'present' ? 'Your NFC attendance is recorded for today and visible to teachers in real time.' : 'Tap your NFC ID card on the attendance phone to mark today’s presence.'}</p><button className="text-btn">View detailed insights <Icon>arrow_forward</Icon></button></div></Card><Card><div className="accordion"><h2>Personal Details</h2><Icon>expand_more</Icon></div><div className="detail-grid">{[['Email', 'shashi.kant@edusync.edu'], ['Phone', '+91 98765 43210'], ['Date of birth', '14 August 2007'], ['Guardian', 'Ramesh Kant']].map(([label, value]) => <span key={label}>{label}<strong>{value}</strong></span>)}</div></Card></StudentLayout>; }

export function Result() { const rows = [['Mathematics', '92', 'A+', 'Passed'], ['Physics', '86', 'A', 'Passed'], ['Chemistry', '78', 'B+', 'Passed'], ['English', '88', 'A', 'Passed'], ['Computer Science', '95', 'A+', 'Passed']]; return <StudentLayout><div className="result-top"><button className="icon-btn"><Icon>arrow_back</Icon></button><div><h1>Final Semester Exam</h1><p>Academic Year 2024–25 • December 2024</p></div><button className="outline-btn"><Icon>download</Icon>Download</button></div><div className="result-stats">{[['#04', 'CLASS RANK'], ['4.2', 'GPA'], ['Passed', 'RESULT']].map(([value, label]) => <Card key={label}><span>{label}</span><strong>{value}</strong></Card>)}</div><Card><h2>Marksheet</h2><div className="table-wrap"><table><thead><tr><th>Subject</th><th>Marks</th><th>Grade</th><th>Status</th></tr></thead><tbody>{rows.map(([subject, marks, grade, status]) => <tr key={subject}><td><b>{subject}</b></td><td>{marks} / 100</td><td>{grade}</td><td><Status>{status}</Status></td></tr>)}</tbody></table></div></Card></StudentLayout>; }
