import { Card, Icon, PageHeader, Status } from '../../components/common/ui';
import { StudentLayout } from '../../components/layouts';
import type { Role } from '../../app/App';

export function Login({ onLogin }: { onLogin: (role: Role) => void }) {
  return <main className="login-page"><section className="login-card"><div className="brand login-brand"><span className="brand-mark"><Icon>school</Icon></span>EduSync ERP</div><span className="eyebrow">WELCOME BACK</span><h1>Sign in to your campus</h1><p className="login-subtitle">Choose your workspace to continue.</p><div className="role-options"><button onClick={() => onLogin('student')}><span className="role-icon student-role"><Icon>school</Icon></span><span><strong>Student Login</strong><small>View assignments, results and profile</small></span><Icon>arrow_forward</Icon></button><button onClick={() => onLogin('admin')}><span className="role-icon admin-role"><Icon>admin_panel_settings</Icon></span><span><strong>Admin Login</strong><small>Manage exams, paperwork and activities</small></span><Icon>arrow_forward</Icon></button></div><p className="demo-note"><Icon>info</Icon>Local demo mode: no password required.</p></section></main>;
}

export function StudentDashboard() { const events = [['science', 'Science Exhibition', '20 Days Left'], ['celebration', 'Annual Function Day', '5 Days Left'], ['today', 'My Day', '7 Days Left']]; return <StudentLayout><PageHeader title="Hello, Shashi Kant!" subtitle="Here's your academic overview for today." /><section className="section"><h2>Upcoming Events</h2><div className="event-grid">{events.map(([icon, title, date]) => <Card className="event-card" key={title}><div className="event-icon"><Icon>{icon}</Icon></div><div><b>{title}</b><span>{date}</span></div><Icon>chevron_right</Icon></Card>)}</div></section><Card className="announcement"><div><span className="label">ANNOUNCEMENT</span><h2>Important Update:<br />School Holiday</h2><p>Due to national holiday, the campus will remain closed this Friday.</p><button className="light-btn">Read more <Icon>arrow_forward</Icon></button></div><Icon>campaign</Icon></Card><Card><h2>My Progress</h2><div className="progress-chart">{[65, 78, 58, 86, 72, 92, 80].map((height, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${height}%` }} /><span>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][i]}</span></div>)}</div></Card></StudentLayout>; }

export function Assignments() { const items = [['Compiler Design Lab 4', 'Compiler Design', 'Due tomorrow', 'Pending'], ['Flutter UI Prototype', 'Mobile Application', 'Due Oct 30', 'Submitted'], ['Neural Networks Research Paper', 'Artificial Intelligence', 'Due Nov 05', 'Graded']]; return <StudentLayout><PageHeader title="Assignments" subtitle="Keep track of your coursework and deadlines." action="New Assignment" /><div className="filter-row">{['All', 'Pending', 'Submitted', 'Graded'].map((filter, i) => <button className={`filter ${i === 0 ? 'active' : ''}`} key={filter}>{filter}</button>)}</div>{items.map(([title, subject, due, status]) => <Card className="assignment" key={title}><div className="subject-icon"><Icon>description</Icon></div><div className="assignment-info"><span className="eyebrow">{subject}</span><h2>{title}</h2><p><Icon>calendar_today</Icon>{due}</p></div><Status>{status}</Status><button className="icon-btn"><Icon>more_vert</Icon></button></Card>)}</StudentLayout>; }

export function Profile() { const stats = [['4.2', 'GPA'], ['94%', 'Attendance'], ['12/15', 'Assignments']]; return <StudentLayout><Card className="profile-hero"><div className="profile-avatar">SK</div><div><h1>Shashi Kant</h1><p>Grade 12 • Section A</p><span className="muted">Student ID: STU-2024-018</span></div><button className="outline-btn"><Icon>edit</Icon>Edit profile</button></Card><div className="stats">{stats.map(([value, label]) => <Card key={label}><strong>{value}</strong><span>{label}</span></Card>)}</div><Card className="insight"><div className="insight-icon"><Icon>auto_awesome</Icon></div><div><span className="eyebrow">AI PERFORMANCE INSIGHT</span><h2>You're building strong momentum</h2><p>Your performance in science subjects has improved by 12% this term.</p><button className="text-btn">View detailed insights <Icon>arrow_forward</Icon></button></div></Card><Card><div className="accordion"><h2>Personal Details</h2><Icon>expand_more</Icon></div><div className="detail-grid">{[['Email', 'shashi.kant@edusync.edu'], ['Phone', '+91 98765 43210'], ['Date of birth', '14 August 2007'], ['Guardian', 'Ramesh Kant']].map(([label, value]) => <span key={label}>{label}<strong>{value}</strong></span>)}</div></Card></StudentLayout>; }

export function Result() { const rows = [['Mathematics', '92', 'A+', 'Passed'], ['Physics', '86', 'A', 'Passed'], ['Chemistry', '78', 'B+', 'Passed'], ['English', '88', 'A', 'Passed'], ['Computer Science', '95', 'A+', 'Passed']]; return <StudentLayout><div className="result-top"><button className="icon-btn"><Icon>arrow_back</Icon></button><div><h1>Final Semester Exam</h1><p>Academic Year 2024–25 • December 2024</p></div><button className="outline-btn"><Icon>download</Icon>Download</button></div><div className="result-stats">{[['#04', 'CLASS RANK'], ['4.2', 'GPA'], ['Passed', 'RESULT']].map(([value, label]) => <Card key={label}><span>{label}</span><strong>{value}</strong></Card>)}</div><Card><h2>Marksheet</h2><div className="table-wrap"><table><thead><tr><th>Subject</th><th>Marks</th><th>Grade</th><th>Status</th></tr></thead><tbody>{rows.map(([subject, marks, grade, status]) => <tr key={subject}><td><b>{subject}</b></td><td>{marks} / 100</td><td>{grade}</td><td><Status>{status}</Status></td></tr>)}</tbody></table></div></Card></StudentLayout>; }
